// Code generated by protoc-gen-go.
// source: sonny.proto
// DO NOT EDIT!

/*
Package sonny is a generated protocol buffer package.

It is generated from these files:
	sonny.proto

It has these top-level messages:
	HeadingRet
	LEDBlinkReq
	LEDOnReq
	PIRRet
	ServoReq
*/
package sonny

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HeadingRet struct {
	Heading float64 `protobuf:"fixed64,1,opt,name=heading" json:"heading,omitempty"`
}

func (m *HeadingRet) Reset()                    { *m = HeadingRet{} }
func (m *HeadingRet) String() string            { return proto.CompactTextString(m) }
func (*HeadingRet) ProtoMessage()               {}
func (*HeadingRet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type LEDBlinkReq struct {
	Duration uint32 `protobuf:"varint,1,opt,name=duration" json:"duration,omitempty"`
	Times    uint32 `protobuf:"varint,2,opt,name=times" json:"times,omitempty"`
}

func (m *LEDBlinkReq) Reset()                    { *m = LEDBlinkReq{} }
func (m *LEDBlinkReq) String() string            { return proto.CompactTextString(m) }
func (*LEDBlinkReq) ProtoMessage()               {}
func (*LEDBlinkReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type LEDOnReq struct {
	On bool `protobuf:"varint,1,opt,name=On" json:"On,omitempty"`
}

func (m *LEDOnReq) Reset()                    { *m = LEDOnReq{} }
func (m *LEDOnReq) String() string            { return proto.CompactTextString(m) }
func (*LEDOnReq) ProtoMessage()               {}
func (*LEDOnReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type PIRRet struct {
	On bool `protobuf:"varint,1,opt,name=On" json:"On,omitempty"`
}

func (m *PIRRet) Reset()                    { *m = PIRRet{} }
func (m *PIRRet) String() string            { return proto.CompactTextString(m) }
func (*PIRRet) ProtoMessage()               {}
func (*PIRRet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ServoReq struct {
	Servo uint32 `protobuf:"varint,1,opt,name=servo" json:"servo,omitempty"`
	Angle uint32 `protobuf:"varint,2,opt,name=angle" json:"angle,omitempty"`
}

func (m *ServoReq) Reset()                    { *m = ServoReq{} }
func (m *ServoReq) String() string            { return proto.CompactTextString(m) }
func (*ServoReq) ProtoMessage()               {}
func (*ServoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*HeadingRet)(nil), "sonny.HeadingRet")
	proto.RegisterType((*LEDBlinkReq)(nil), "sonny.LEDBlinkReq")
	proto.RegisterType((*LEDOnReq)(nil), "sonny.LEDOnReq")
	proto.RegisterType((*PIRRet)(nil), "sonny.PIRRet")
	proto.RegisterType((*ServoReq)(nil), "sonny.ServoReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for DevicesRPC service

type DevicesRPCClient interface {
	Ping(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	LEDBlink(ctx context.Context, in *LEDBlinkReq, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	LEDOn(ctx context.Context, in *LEDOnReq, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	Heading(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*HeadingRet, error)
	PIRDetect(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*PIRRet, error)
	ServoRotate(ctx context.Context, in *ServoReq, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type devicesRPCClient struct {
	cc *grpc.ClientConn
}

func NewDevicesRPCClient(cc *grpc.ClientConn) DevicesRPCClient {
	return &devicesRPCClient{cc}
}

func (c *devicesRPCClient) Ping(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/sonny.DevicesRPC/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesRPCClient) LEDBlink(ctx context.Context, in *LEDBlinkReq, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/sonny.DevicesRPC/LEDBlink", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesRPCClient) LEDOn(ctx context.Context, in *LEDOnReq, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/sonny.DevicesRPC/LEDOn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesRPCClient) Heading(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*HeadingRet, error) {
	out := new(HeadingRet)
	err := grpc.Invoke(ctx, "/sonny.DevicesRPC/Heading", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesRPCClient) PIRDetect(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*PIRRet, error) {
	out := new(PIRRet)
	err := grpc.Invoke(ctx, "/sonny.DevicesRPC/PIRDetect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesRPCClient) ServoRotate(ctx context.Context, in *ServoReq, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/sonny.DevicesRPC/ServoRotate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DevicesRPC service

type DevicesRPCServer interface {
	Ping(context.Context, *google_protobuf.Empty) (*google_protobuf.Empty, error)
	LEDBlink(context.Context, *LEDBlinkReq) (*google_protobuf.Empty, error)
	LEDOn(context.Context, *LEDOnReq) (*google_protobuf.Empty, error)
	Heading(context.Context, *google_protobuf.Empty) (*HeadingRet, error)
	PIRDetect(context.Context, *google_protobuf.Empty) (*PIRRet, error)
	ServoRotate(context.Context, *ServoReq) (*google_protobuf.Empty, error)
}

func RegisterDevicesRPCServer(s *grpc.Server, srv DevicesRPCServer) {
	s.RegisterService(&_DevicesRPC_serviceDesc, srv)
}

func _DevicesRPC_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesRPCServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonny.DevicesRPC/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesRPCServer).Ping(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesRPC_LEDBlink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LEDBlinkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesRPCServer).LEDBlink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonny.DevicesRPC/LEDBlink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesRPCServer).LEDBlink(ctx, req.(*LEDBlinkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesRPC_LEDOn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LEDOnReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesRPCServer).LEDOn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonny.DevicesRPC/LEDOn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesRPCServer).LEDOn(ctx, req.(*LEDOnReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesRPC_Heading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesRPCServer).Heading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonny.DevicesRPC/Heading",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesRPCServer).Heading(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesRPC_PIRDetect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesRPCServer).PIRDetect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonny.DevicesRPC/PIRDetect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesRPCServer).PIRDetect(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesRPC_ServoRotate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesRPCServer).ServoRotate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonny.DevicesRPC/ServoRotate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesRPCServer).ServoRotate(ctx, req.(*ServoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DevicesRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sonny.DevicesRPC",
	HandlerType: (*DevicesRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _DevicesRPC_Ping_Handler,
		},
		{
			MethodName: "LEDBlink",
			Handler:    _DevicesRPC_LEDBlink_Handler,
		},
		{
			MethodName: "LEDOn",
			Handler:    _DevicesRPC_LEDOn_Handler,
		},
		{
			MethodName: "Heading",
			Handler:    _DevicesRPC_Heading_Handler,
		},
		{
			MethodName: "PIRDetect",
			Handler:    _DevicesRPC_PIRDetect_Handler,
		},
		{
			MethodName: "ServoRotate",
			Handler:    _DevicesRPC_ServoRotate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("sonny.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x91, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0x5d, 0xb1, 0x5b, 0x3d, 0x65, 0x8a, 0x41, 0xa4, 0xf4, 0x4a, 0x72, 0x21, 0x5e, 0xf5,
	0x62, 0xca, 0xf0, 0x4e, 0xd0, 0x0e, 0x14, 0x84, 0x95, 0xf8, 0x04, 0xdd, 0x76, 0xac, 0xc1, 0x2d,
	0x99, 0x6d, 0x36, 0xf0, 0x5d, 0x7d, 0x18, 0xf3, 0xaf, 0x9b, 0x08, 0xdd, 0x5d, 0xbe, 0x73, 0xf2,
	0x3b, 0x39, 0xdf, 0x17, 0x88, 0x1b, 0x29, 0xc4, 0x77, 0xb6, 0xae, 0xa5, 0x92, 0x24, 0xb4, 0x22,
	0x8d, 0x71, 0xb5, 0x56, 0xbe, 0x46, 0xaf, 0x01, 0x9e, 0xb1, 0x5c, 0x70, 0x51, 0x31, 0x54, 0x24,
	0x81, 0xc1, 0x87, 0x53, 0x49, 0xef, 0xaa, 0x77, 0xd3, 0x63, 0xad, 0xa4, 0x0f, 0x10, 0xbf, 0x4e,
	0xf2, 0xc7, 0x25, 0x17, 0x9f, 0x0c, 0xbf, 0x48, 0x0a, 0xd1, 0x62, 0x53, 0x97, 0x8a, 0x4b, 0x61,
	0x6f, 0x0e, 0xd9, 0x4e, 0x93, 0x0b, 0x08, 0x15, 0x5f, 0x61, 0x93, 0x04, 0xb6, 0xe1, 0x04, 0xd5,
	0x84, 0x1e, 0x30, 0x15, 0x86, 0x3e, 0x85, 0x60, 0xea, 0xb8, 0x88, 0xe9, 0x13, 0x4d, 0xa0, 0x5f,
	0xbc, 0x30, 0xb3, 0xc0, 0xff, 0xce, 0x18, 0xa2, 0x37, 0xac, 0xb7, 0xd2, 0x50, 0x7a, 0x6e, 0x63,
	0xce, 0xfe, 0x41, 0x27, 0x4c, 0xb5, 0x14, 0xd5, 0x12, 0xdb, 0xd7, 0xac, 0x18, 0xfd, 0x04, 0x00,
	0x39, 0x6e, 0xf9, 0x1c, 0x1b, 0x56, 0x3c, 0x91, 0x7b, 0x38, 0x2e, 0xb4, 0x0b, 0x72, 0x99, 0x55,
	0x52, 0xea, 0xbe, 0x33, 0x3f, 0xdb, 0xbc, 0x67, 0x13, 0x93, 0x45, 0xda, 0x51, 0xa7, 0x47, 0x9a,
	0x8c, 0x5a, 0xdf, 0x84, 0x64, 0x2e, 0xcd, 0x3f, 0x41, 0x1c, 0x20, 0x47, 0x10, 0x5a, 0xc3, 0xe4,
	0x6c, 0x8f, 0x59, 0xfb, 0x07, 0x98, 0x31, 0x0c, 0xfc, 0x6f, 0x74, 0xae, 0x7a, 0xee, 0xa7, 0xed,
	0x7f, 0x4d, 0x73, 0x77, 0x70, 0xa2, 0x03, 0xcc, 0x51, 0xe1, 0x5c, 0x75, 0x92, 0x43, 0x4f, 0xba,
	0xa8, 0xad, 0xb7, 0xd8, 0x85, 0x2b, 0x55, 0xa9, 0x70, 0xb7, 0x67, 0x1b, 0x78, 0xf7, 0x9e, 0xb3,
	0xbe, 0xad, 0xdc, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x23, 0xd5, 0x39, 0x5f, 0x02, 0x00,
	0x00,
}
